# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(9, 39, 551, 261))
        self.mdiArea.setViewMode(QtWidgets.QMdiArea.SubWindowView)
        self.mdiArea.setTabsClosable(True)
        self.mdiArea.setObjectName("mdiArea")
        self.extra_info_subwindow = QtWidgets.QWidget()
        self.extra_info_subwindow.setObjectName("extra_info_subwindow")
        self.label_4 = QtWidgets.QLabel(self.extra_info_subwindow)
        self.label_4.setGeometry(QtCore.QRect(60, 20, 67, 17))
        self.label_4.setObjectName("label_4")
        self.age_lineEdit = QtWidgets.QLineEdit(self.extra_info_subwindow)
        self.age_lineEdit.setGeometry(QtCore.QRect(50, 50, 113, 25))
        self.age_lineEdit.setObjectName("age_lineEdit")
        self.family_subwindow = QtWidgets.QWidget()
        self.family_subwindow.setObjectName("family_subwindow")
        self.label_3 = QtWidgets.QLabel(self.family_subwindow)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 67, 17))
        self.label_3.setObjectName("label_3")
        self.family_lineEdit = QtWidgets.QLineEdit(self.family_subwindow)
        self.family_lineEdit.setGeometry(QtCore.QRect(40, 50, 113, 25))
        self.family_lineEdit.setObjectName("family_lineEdit")
        self.name_subwindow = QtWidgets.QWidget()
        self.name_subwindow.setObjectName("name_subwindow")
        self.label_2 = QtWidgets.QLabel(self.name_subwindow)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 67, 17))
        self.label_2.setObjectName("label_2")
        self.name_lineEdit = QtWidgets.QLineEdit(self.name_subwindow)
        self.name_lineEdit.setGeometry(QtCore.QRect(30, 90, 113, 25))
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 370, 67, 17))
        self.label.setObjectName("label")
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        self.info_label.setGeometry(QtCore.QRect(50, 410, 131, 81))
        self.info_label.setObjectName("info_label")
        self.show_button = QtWidgets.QPushButton(self.centralwidget)
        self.show_button.setGeometry(QtCore.QRect(40, 320, 89, 25))
        self.show_button.setObjectName("show_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_sub = QtWidgets.QAction(MainWindow)
        self.action_sub.setObjectName("action_sub")
        self.action_tabbed = QtWidgets.QAction(MainWindow)
        self.action_tabbed.setObjectName("action_tabbed")
        self.actionCascade = QtWidgets.QAction(MainWindow)
        self.actionCascade.setObjectName("actionCascade")
        self.actionTile = QtWidgets.QAction(MainWindow)
        self.actionTile.setObjectName("actionTile")
        self.menuWindow.addAction(self.action_sub)
        self.menuWindow.addAction(self.action_tabbed)
        self.menuWindow.addAction(self.actionCascade)
        self.menuWindow.addAction(self.actionTile)
        self.menubar.addAction(self.menuWindow.menuAction())

        self.retranslateUi(MainWindow)
        self.actionCascade.triggered.connect(MainWindow.show)
        self.action_tabbed.triggered.connect(MainWindow.show)
        self.action_sub.triggered.connect(MainWindow.show)
        self.actionTile.triggered.connect(MainWindow.show)
        self.show_button.clicked.connect(MainWindow.update_info)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.extra_info_subwindow.setWindowTitle(_translate("MainWindow", "Extra_info"))
        self.label_4.setText(_translate("MainWindow", "age"))
        self.family_subwindow.setWindowTitle(_translate("MainWindow", "Family"))
        self.label_3.setText(_translate("MainWindow", "Family"))
        self.name_subwindow.setWindowTitle(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label.setText(_translate("MainWindow", "My Info"))
        self.info_label.setText(_translate("MainWindow", "TextLabel"))
        self.show_button.setText(_translate("MainWindow", "Show"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.action_sub.setText(_translate("MainWindow", "Sub View"))
        self.action_tabbed.setText(_translate("MainWindow", "Tabbed"))
        self.actionCascade.setText(_translate("MainWindow", "Cascade"))
        self.actionTile.setText(_translate("MainWindow", "Tile"))
