# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(524, 524)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 80, 99, 17))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 300, 261, 191))
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_3.setMouseTracking(True)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setLineWidth(1)
        self.label_3.setText("")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setPixmap(QtGui.QPixmap("/home/ali/Projects/GUI-with-Python/PyQt Designner/Book_Exercises/Grouping Radio Buttoms/images.jpeg"))
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(60, 120, 114, 112))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.meduim = QtWidgets.QRadioButton(self.widget)
        self.meduim.setObjectName("meduim")
        self.verticalLayout.addWidget(self.meduim)
        self.small = QtWidgets.QRadioButton(self.widget)
        self.small.setObjectName("small")
        self.verticalLayout.addWidget(self.small)
        self.large = QtWidgets.QRadioButton(self.widget)
        self.large.setObjectName("large")
        self.verticalLayout.addWidget(self.large)
        self.xlarge = QtWidgets.QRadioButton(self.widget)
        self.xlarge.setObjectName("xlarge")
        self.verticalLayout.addWidget(self.xlarge)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(340, 130, 114, 83))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.m1 = QtWidgets.QRadioButton(self.widget1)
        self.m1.setObjectName("m1")
        self.verticalLayout_2.addWidget(self.m1)
        self.m2 = QtWidgets.QRadioButton(self.widget1)
        self.m2.setObjectName("m2")
        self.verticalLayout_2.addWidget(self.m2)
        self.m3 = QtWidgets.QRadioButton(self.widget1)
        self.m3.setObjectName("m3")
        self.verticalLayout_2.addWidget(self.m3)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(320, 80, 126, 17))
        self.label_2.setObjectName("label_2")
        self.widget2 = QtWidgets.QWidget(Dialog)
        self.widget2.setGeometry(QtCore.QRect(300, 310, 137, 151))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.price_label = QtWidgets.QLabel(self.widget2)
        self.price_label.setObjectName("price_label")
        self.verticalLayout_3.addWidget(self.price_label)
        self.cal = QtWidgets.QPushButton(self.widget2)
        self.cal.setObjectName("cal")
        self.verticalLayout_3.addWidget(self.cal)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "My app"))
        self.label.setText(_translate("Dialog", "Select the Size"))
        self.label_3.setWhatsThis(_translate("Dialog", "<html><head/><body><p>this is show label</p><p><br/></p></body></html>"))
        self.meduim.setText(_translate("Dialog", "M"))
        self.small.setText(_translate("Dialog", "S"))
        self.large.setText(_translate("Dialog", "L"))
        self.xlarge.setText(_translate("Dialog", "XL"))
        self.m1.setText(_translate("Dialog", "method_1"))
        self.m2.setText(_translate("Dialog", "method_2"))
        self.m3.setText(_translate("Dialog", "method_3"))
        self.label_2.setText(_translate("Dialog", "Select the Method"))
        self.price_label.setText(_translate("Dialog", "TextLabel"))
        self.cal.setText(_translate("Dialog", "Calculate the Price"))
