#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Feb 07, 2020 05:56:07 PM +0330  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Hello_world_with_page_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    Hello_world_with_page_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    Hello_world_with_page_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'

        top.geometry("600x450+354+171")
        top.minsize(1, 1)
        top.maxsize(1351, 738)
        top.resizable(1, 1)
        top.title("New Toplevel")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.267, rely=0.556, height=25, width=63)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(text='''Hello''')

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.617, rely=0.556, height=25, width=84)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(text='''Good Bye''')

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.3, rely=0.156, height=105, width=249)
        self.Label1.configure(text='''Hello there''')

if __name__ == '__main__':
    vp_start_gui()





